In [ ]:
import numpy as np

In [ ]:
data=np.random.randint(0,10,(3,3))

In [ ]:
data

array([[1, 2, 3],
       [2, 3, 1],
       [8, 8, 6]])

In [ ]:
data.sum()

np.int64(34)

In [ ]:
data.sum(axis=1)

array([ 6,  6, 22])

In [ ]:
data.sum(axis=0)

array([11, 13, 10])

In [ ]:
data.max()

np.int64(8)

In [ ]:
data.max(axis=1)

array([3, 3, 8])

In [ ]:
data.max(axis=0)

array([8, 8, 6])

In [ ]:
data.min(axis=1)

array([1, 1, 6])

In [ ]:
data

array([[1, 2, 3],
       [2, 3, 1],
       [8, 8, 6]])

In [ ]:
data.min(axis=0)

array([1, 2, 1])

In [ ]:
data.argmax(axis=1)

array([2, 1, 0])

In [ ]:
data=np.random.randint(0,100,(10,5))

In [ ]:
data

array([[89, 60, 51, 87, 50],
       [60, 99, 44, 83, 68],
       [13, 47, 35, 48, 41],
       [35, 43, 69, 81,  4],
       [81, 89, 45, 41, 37],
       [ 0, 50, 26, 35, 43],
       [29, 22, 49, 28, 89],
       [92,  5, 49, 80, 46],
       [92, 73, 54, 18, 36],
       [62, 83, 51, 98, 40]])

In [ ]:
data.sum(axis=1)

array([337, 354, 184, 232, 293, 154, 217, 272, 273, 334])

In [ ]:
data.sum(axis=0)[3:].sum()

np.int64(1053)

In [ ]:
data[:,3:5].sum()

np.int64(1053)

In [ ]:
data.sum(axis=1).argmin()+1

np.int64(6)

In [ ]:
data.sum(axis=0).argmax()+1

np.int64(4)

In [ ]:
data.min(axis=0).max()-data.min(axis=0).min()

np.int64(26)

In [ ]:
data=np.random.randint(0,10,10)

In [ ]:
data

array([5, 2, 3, 9, 8, 4, 8, 9, 5, 8])

In [ ]:
data.mean()

np.float64(6.1)

In [ ]:
data

array([5, 2, 3, 9, 8, 4, 8, 9, 5, 8])

In [ ]:
np.median(data)

np.float64(6.5)

In [ ]:
data

array([5, 2, 3, 9, 8, 4, 8, 9, 5, 8])

In [ ]:
np.quantile(data,0.25)

np.float64(4.25)

In [ ]:
np.quantile(data,0.50)

np.float64(6.5)

In [ ]:
np.quantile(data,0.75)

np.float64(8.0)

In [ ]:
np.std(data)

np.float64(2.467792535850613)

In [ ]:
np.var(data)

np.float64(6.09)

In [ ]:
data=np.random.randint(0,10,(10,2))

In [ ]:
np.corrcoef(data.T)

array([[ 1.        , -0.63982373],
       [-0.63982373,  1.        ]])

In [ ]:
v1=np.arange(1,11)

In [ ]:
v2=np.arange(10,20)

In [ ]:
v1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
v2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
x=[10,11,12,13,14,15,16,17,18,19]
x.reverse()
v2=np.array(x)
v2

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

In [ ]:
data[:,0]=v1
data[:,1]=v2

In [ ]:
np.corrcoef(data.T)

array([[ 1., -1.],
       [-1.,  1.]])

In [ ]:
data=np.random.randint(0,10,(5,5))

In [ ]:
np.corrcoef(data)

array([[ 1.        , -0.47287799, -0.68802092, -0.59946195, -0.11337898],
       [-0.47287799,  1.        ,  0.44410268, -0.23865673,  0.79735369],
       [-0.68802092,  0.44410268,  1.        , -0.05106429, -0.17239571],
       [-0.59946195, -0.23865673, -0.05106429,  1.        , -0.15819985],
       [-0.11337898,  0.79735369, -0.17239571, -0.15819985,  1.        ]])