In [ ]:
import numpy as np

In [ ]:
list(),str(),tuple(),set(),dict()

([], '', (), set(), {})

In [ ]:
y=np.array([1,2,3,4,5])

In [ ]:
x=[1,2,3]

In [ ]:
type(x),type(y)

(list, numpy.ndarray)

In [ ]:
x/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [ ]:
y/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [ ]:
x=[1,2,3,"data science"]

In [ ]:
x

[1, 2, 3, 'data science']

In [ ]:
type(x[0]),type(x[1]),type(x[2]),type(x[3])

(int, int, int, str)

In [ ]:
y=np.array([1,2,3.4,"data science"])

In [ ]:
type(y[0]),type(y[1]),type(y[2]),type(y[3])

(numpy.str_, numpy.str_, numpy.str_, numpy.str_)

In [ ]:
for i in range(1,10):
  print(np.random.randint(0,10))

0
8
0
6
7
3
3
7
9


In [ ]:
np.random.randint(0,10,(3,3))

array([[8, 0, 4],
       [6, 4, 8],
       [8, 1, 4]])

In [ ]:
data=np.random.randint(0,100,(5,5))

In [ ]:
data

array([[32, 93, 29, 83, 13],
       [88, 83, 58, 85, 37],
       [33, 26, 73, 76, 35],
       [83, 74, 29, 64, 69],
       [90, 55,  2, 14, 50]])

In [ ]:
data[1:3,4:5]

array([[37],
       [35]])

In [ ]:
data[-5:-4,-5:-3]

array([[32, 93]])

In [ ]:
data

array([[32, 93, 29, 83, 13],
       [88, 83, 58, 85, 37],
       [33, 26, 73, 76, 35],
       [83, 74, 29, 64, 69],
       [90, 55,  2, 14, 50]])

In [ ]:
data[-3:-1,-3:-1]

array([[73, 76],
       [29, 64]])

In [ ]:
data[0,:]

array([32, 93, 29, 83, 13])

In [ ]:
data.shape

(5, 5)

In [ ]:
data.size

25

In [ ]:
data.T

array([[32, 88, 33, 83, 90],
       [93, 83, 26, 74, 55],
       [29, 58, 73, 29,  2],
       [83, 85, 76, 64, 14],
       [13, 37, 35, 69, 50]])

In [ ]:
data

array([[32, 93, 29, 83, 13],
       [88, 83, 58, 85, 37],
       [33, 26, 73, 76, 35],
       [83, 74, 29, 64, 69],
       [90, 55,  2, 14, 50]])

In [ ]:
x=2

In [ ]:
data*2

array([[ 64, 186,  58, 166,  26],
       [176, 166, 116, 170,  74],
       [ 66,  52, 146, 152,  70],
       [166, 148,  58, 128, 138],
       [180, 110,   4,  28, 100]])

In [ ]:
data/2

array([[16. , 46.5, 14.5, 41.5,  6.5],
       [44. , 41.5, 29. , 42.5, 18.5],
       [16.5, 13. , 36.5, 38. , 17.5],
       [41.5, 37. , 14.5, 32. , 34.5],
       [45. , 27.5,  1. ,  7. , 25. ]])

In [ ]:
data+2

array([[34, 95, 31, 85, 15],
       [90, 85, 60, 87, 39],
       [35, 28, 75, 78, 37],
       [85, 76, 31, 66, 71],
       [92, 57,  4, 16, 52]])

In [ ]:
data-2

array([[30, 91, 27, 81, 11],
       [86, 81, 56, 83, 35],
       [31, 24, 71, 74, 33],
       [81, 72, 27, 62, 67],
       [88, 53,  0, 12, 48]])

In [ ]:
data**2

array([[1024, 8649,  841, 6889,  169],
       [7744, 6889, 3364, 7225, 1369],
       [1089,  676, 5329, 5776, 1225],
       [6889, 5476,  841, 4096, 4761],
       [8100, 3025,    4,  196, 2500]])

In [ ]:
data//2

array([[16, 46, 14, 41,  6],
       [44, 41, 29, 42, 18],
       [16, 13, 36, 38, 17],
       [41, 37, 14, 32, 34],
       [45, 27,  1,  7, 25]])

In [ ]:
x=np.random.randint(0,10,(3,3))
y=np.random.randint(0,10,(3,3))

In [ ]:
x

array([[0, 5, 4],
       [2, 1, 9],
       [7, 7, 8]])

In [ ]:
y

array([[2, 6, 2],
       [9, 5, 2],
       [2, 1, 9]])

In [ ]:
np.add(x,2)

array([[ 2,  7,  6],
       [ 4,  3, 11],
       [ 9,  9, 10]])

In [ ]:
np.add(y,2)

array([[ 4,  8,  4],
       [11,  7,  4],
       [ 4,  3, 11]])

In [ ]:
np.multiply(x,2)

array([[ 0, 10,  8],
       [ 4,  2, 18],
       [14, 14, 16]])

In [ ]:
np.divide(x,2)

array([[0. , 2.5, 2. ],
       [1. , 0.5, 4.5],
       [3.5, 3.5, 4. ]])

In [ ]:
np.floor_divide(x,2)

array([[0, 2, 2],
       [1, 0, 4],
       [3, 3, 4]])

In [ ]:
np.exp(x)

array([[1.00000000e+00, 1.48413159e+02, 5.45981500e+01],
       [7.38905610e+00, 2.71828183e+00, 8.10308393e+03],
       [1.09663316e+03, 1.09663316e+03, 2.98095799e+03]])

In [ ]:
np.pow(x,2)

array([[ 0, 25, 16],
       [ 4,  1, 81],
       [49, 49, 64]])

In [ ]:
np.random.rand(5,5)

array([[0.15612698, 0.95208855, 0.57214053, 0.77137814, 0.83946418],
       [0.82671629, 0.40809726, 0.19730136, 0.02615794, 0.24076126],
       [0.83609483, 0.95686822, 0.09734501, 0.58352828, 0.54912476],
       [0.93814167, 0.4592048 , 0.97771123, 0.34764677, 0.70597112],
       [0.42795743, 0.45169472, 0.03199943, 0.00118808, 0.42193548]])

In [ ]:
np.random.rand(1200,1200).std()

np.float64(0.28875912170121193)

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
data=np.random.randint(0,10,(5,5))

In [ ]:
data

array([[2, 7, 5, 1, 4],
       [9, 1, 9, 7, 9],
       [7, 2, 6, 2, 6],
       [8, 5, 4, 5, 9],
       [1, 6, 6, 3, 2]])

In [ ]:
print(data.sum())
print(data.min())
print(data.max())

126
1
9


In [ ]:
data.argmax()

np.int64(5)

In [ ]:
data=np.random.randint(0,10,(3,3))

In [ ]:
data

array([[0, 0, 1],
       [3, 1, 8],
       [5, 8, 9]])

In [ ]:
data.sum(axis=1)

array([ 1, 12, 22])

In [ ]:
data.sum(axis=0)

array([ 8,  9, 18])

In [ ]:
data

array([[0, 0, 1],
       [3, 1, 8],
       [5, 8, 9]])

In [ ]:
data.argmin(axis=1)

array([0, 1, 0])

In [ ]:
data.argmax(axis=1)

array([2, 2, 2])

In [ ]:
data.argmin(axis=0)

array([0, 0, 0])

In [ ]:
data.argmax(axis=0)

array([2, 2, 2])