In [1]:
import numpy as np

In [6]:
data=np.random.randint(0,10,5)

In [7]:
data

array([3, 2, 8, 3, 7])

In [8]:
data+3

array([ 6,  5, 11,  6, 10])

In [11]:
x=np.random.randint(0,10,(4,3))

In [12]:
x

array([[3, 3, 6],
       [8, 5, 9],
       [2, 3, 4],
       [9, 9, 8]])

In [15]:
y=np.random.randint(0,10,3)

In [16]:
y

array([8, 4, 8])

In [17]:
x+y

array([[11,  7, 14],
       [16,  9, 17],
       [10,  7, 12],
       [17, 13, 16]])

In [21]:
x=np.random.randint(0,10,(4,1))

In [22]:
x

array([[0],
       [0],
       [5],
       [6]])

In [24]:
y=np.random.randint(0,10,(1,3))

In [25]:
y

array([[4, 7, 4]])

In [26]:
x+y

array([[ 4,  7,  4],
       [ 4,  7,  4],
       [ 9, 12,  9],
       [10, 13, 10]])

In [49]:
data=np.loadtxt("/content/sample.txt")

In [51]:
data

array([[1., 2., 3., 4., 5.],
       [5., 6., 7., 9., 7.],
       [1., 2., 4., 5., 7.],
       [8., 5., 6., 7., 8.],
       [8., 6., 5., 4., 3.]])

In [50]:
data.shape

(5, 5)

In [41]:
import glob

In [52]:
glob.glob("/content/*.txt")

['/content/sample.file2.txt',
 '/content/sample.file.txt',
 '/content/sample.txt']

In [53]:
data=np.loadtxt("/content/sample.txt")

In [54]:
data

array([[1., 2., 3., 4., 5.],
       [5., 6., 7., 9., 7.],
       [1., 2., 4., 5., 7.],
       [8., 5., 6., 7., 8.],
       [8., 6., 5., 4., 3.]])

In [55]:
data=np.loadtxt("/content/sample.txt")
paths=glob.glob("/content/*.txt")

In [57]:
paths

['/content/sample.file2.txt',
 '/content/sample.file.txt',
 '/content/sample.txt']

In [59]:
for i in paths:
  data=np.loadtxt(i)
  print(data)
  print(" ")

[[11. 12. 13.]
 [14. 15. 16.]
 [17. 19. 20.]]
 
[[9. 8. 7.]
 [6. 5. 4.]
 [3. 2. 1.]]
 
[[1. 2. 3. 4. 5.]
 [5. 6. 7. 9. 7.]
 [1. 2. 4. 5. 7.]
 [8. 5. 6. 7. 8.]
 [8. 6. 5. 4. 3.]]
 


In [62]:
np.loadtxt("/content/test.csv",delimiter=',')

<ipython-input-62-95ae3510b42f>:1: UserWarning: loadtxt: input contained no data: "/content/test.csv"
  np.loadtxt("/content/test.csv",delimiter=',')


array([], dtype=float64)

In [66]:
data=np.random.randint(0,10,5)

In [67]:
data

array([0, 2, 2, 2, 5])

In [68]:
data.cumsum()

array([ 0,  2,  4,  6, 11])

In [69]:
data.cumprod()

array([0, 0, 0, 0, 0])

In [71]:
data=np.random.randint(0,10,(3,3))

In [72]:
data

array([[0, 4, 1],
       [2, 6, 0],
       [9, 2, 2]])

In [74]:
data.cumsum(axis=1)

array([[ 0,  4,  5],
       [ 2,  8,  8],
       [ 9, 11, 13]])

In [75]:
data.cumprod(axis=1)

array([[ 0,  0,  0],
       [ 2, 12,  0],
       [ 9, 18, 36]])

In [76]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [77]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [78]:
a=np.random.choice([10,20,30,40,50],size=3)
a

array([50, 50, 50])

In [79]:
a=np.random.choice([10,20,30,40,50],size=3,replace=True)
a

array([20, 10, 20])

In [80]:
a=np.random.choice([10,20,30,40,50],size=3,replace=False)
a

array([40, 10, 20])