In [ ]:
import numpy as np

In [ ]:
#Retail dataset as numpy array
retail_np_array = np.array([
    [1001, "Laptop", 1, 50000, 50000],
    [1002, "Mouse", 2, 500, 1000],
    [1003, "Keyboard", 1, 1000, 1000],
    [1004, "Momitor", 2, 7000, 14000],
    [1005, "Headphones", 1, 2000, 2000]
], dtype=object)
retail_np_array

array([[1001, 'Laptop', 1, 50000, 50000],
       [1002, 'Mouse', 2, 500, 1000],
       [1003, 'Keyboard', 1, 1000, 1000],
       [1004, 'Momitor', 2, 7000, 14000],
       [1005, 'Headphones', 1, 2000, 2000]], dtype=object)

In [ ]:
#Extracting columns
customer_ids = retail_np_array[:, 0]
products = retail_np_array[:, 1]
qunatities = retail_np_array[:, 2].astype(int)
prices = retail_np_array[:, 3].astype(int)
totals = retail_np_array[:, 4].astype(int)
retail_np_array

array([[1001, 'Laptop', 1, 50000, 50000],
       [1002, 'Mouse', 2, 500, 1000],
       [1003, 'Keyboard', 1, 1000, 1000],
       [1004, 'Momitor', 2, 7000, 14000],
       [1005, 'Headphones', 1, 2000, 2000]], dtype=object)

In [ ]:
retail_np_array.shape[0]

5

In [ ]:
np.sum(totals)

np.int64(68000)

In [ ]:
np.mean(totals)

np.float64(13600.0)

In [ ]:
products[np.argmax(totals)]

'Laptop'

In [ ]:
products[np.argmin(totals)]

'Mouse'

In [ ]:
np.mean(prices)

np.float64(12100.0)

In [ ]:
np.sum(qunatities)

np.int64(7)

In [ ]:
np.unique(products,return_counts=True)

(array(['Headphones', 'Keyboard', 'Laptop', 'Momitor', 'Mouse'],
       dtype=object),
 array([1, 1, 1, 1, 1]))

In [ ]:
len(np.unique(products))

5

In [ ]:
len(np.unique(customer_ids))

5

In [ ]:
products.tolist()

['Laptop', 'Mouse', 'Keyboard', 'Momitor', 'Headphones']

In [ ]:
{prod:np.sum(totals[products==prod]) for prod in np.unique(products)}

{'Headphones': np.int64(2000),
 'Keyboard': np.int64(1000),
 'Laptop': np.int64(50000),
 'Momitor': np.int64(14000),
 'Mouse': np.int64(1000)}

In [ ]:
{prod:np.sum(qunatities[products==prod]) for prod in np.unique(products)}

{'Headphones': np.int64(1),
 'Keyboard': np.int64(1),
 'Laptop': np.int64(1),
 'Momitor': np.int64(2),
 'Mouse': np.int64(2)}

In [ ]:
np.max(prices)

np.int64(50000)

In [ ]:
np.min(prices)

np.int64(500)

In [ ]:
products[qunatities>1].tolist()

['Mouse', 'Momitor']

In [ ]:
customer_ids[qunatities>1].tolist()

[1002, 1004]

In [ ]:
np.sum(totals[customer_ids==1002])

np.int64(1000)

In [ ]:
products[prices>1000].tolist()

['Laptop', 'Momitor', 'Headphones']

In [ ]:
products[totals>=2000].tolist()

['Laptop', 'Momitor', 'Headphones']